# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-04 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_auto_20181103_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='connexion',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='connexion',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connexion',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
